name: $[ variables['branchName'] ]

# Using conditions to set the variable value. 
# I guess if both conditions return true the last will be used.
variables:
  ${{ if startsWith(variables['Build.SourceBranch'], 'refs/heads/') }}:
    branchName: $[ replace(variables['Build.SourceBranch'], 'refs/heads/', '') ]
  ${{ if startsWith(variables['Build.SourceBranch'], 'refs/pull/') }}:
    branchName: $[ replace(variables['System.PullRequest.SourceBranch'], 'refs/heads/', '') ]

trigger:
- master

# pr: none

pool:
  vmImage: 'ubuntu-20.04'

steps:
- script: |
    git checkout $(Build.SourceBranchName)
    git remote add heroku https://heroku:$(heroku_token)@git.heroku.com/delta-frontend.git
    git push heroku $(Build.SourceBranchName)
  displayName: 'Delta Frontend Heroku Deployment'
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')

- script: |
    cd tests/end_to_end
    npm install
    npm run test:staging
  displayName: 'Delta Frontend - Staging End to End Tests'
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')

- script: |
    npm install
    npm run lint
    npm run build
  displayName: 'Delta Frontend - PR Check'
  condition: ne(variables['Build.SourceBranch'], 'refs/heads/master')

- script: |
    ./node_modules/.bin/next &
    cd tests/end_to_end
    npm install
    npm run test:preview
  displayName: 'Delta Frontend - PR End to End Tests Check'
  condition: ne(variables['Build.SourceBranch'], 'refs/heads/master')

- script: |
    cd tests/end_to_end
    ARGOS_COMMIT=$(Build.SourceVersion) ARGOS_BRANCH=$(branchName) \
    ./node_modules/.bin/argos upload screenshots/reference --token $(ARGOS_TOKEN) || true
  displayName: 'Delta Frontend - Screenshots upload to Argos'
